<?php
/**
 * @category    CleverSoft
 * @package     CleverProduct
 * @copyright   Copyright © 2017 CleverSoft., JSC. All Rights Reserved.
 * @author 		ZooExtension.com
 * @email       magento.cleversoft@gmail.com
 */
?>
<?php
use Magento\Framework\App\Action\Action;
/* @var $this CleverProduct_Block_Widget */
$id         = $block->getConfig('id') ? $block->getConfig('id') : $block->getData('id');
//$_template = $block->getTemplate();
$productCollection  = $block->getData('collection');
$_template = ($block->getData('layout') == 'list') ? 'zoo-product-collection02' : 'zoo-product-collection01';
$title      = $block->getData('widget_title');
$tabs       = $block->getTabs();
$t          = microtime();
$type = $block->getData('layout');
// zoo-product-collection01 = grid layout, zoo-product-collection02 = list layout
$template = 'widget/cases/tab_grid2_items.phtml';
$count              = $productCollection ? $productCollection->count() : 0;
$column             = $block->getData('column_grid2');
$carousel = 0;
?>
<div class="<?php echo $block->getData('classes') . ' ' . $_template ?> " id="<?php echo $id ?>">
    <div class="tabs-collection">
            <div class="zoo-heading-wrapper-title">
                <?php if ($title): ?>
                    <h3><?php echo $title ?></h3>
                <?php endif ?>
            </div>
        <ul class="widget-tabs nav nav-tabs">
            <?php foreach ($tabs as $index => $tab): ?>
                <li class="<?php echo $index==0 ? 'active' : '' ?>">
                    <a href="#<?php echo $id . '-' . $tab['id'] ?>"
                       data-value="<?php echo $tab['value'] ?>"
                       data-id="<?php echo $id ?>"
                       data-type="<?php echo $tab['type'] ?>"
                       data-limit="<?php echo $block->getLimit() ?>"
                       data-column_ajax="<?php echo $column ?>"
                       data-layout="<?php echo $type ?>"
                       data-cpid="<?php echo $tab['cpid'] ?>"
                       data-cid="<?php echo $block->getData('category_ids') ?>"
                       data-template="<?php echo $template ?>"
                       data-image_width="<?php echo $block->getData('image_width') ?>"
                       data-image_height="<?php echo $block->getData('image_height') ?>"
                       data-lazyload="<?php echo $block->getData('lazyload') ?>"
                       data-height_image="<?php echo $block->getData('height_image') ?>"
                       data-display_rating="<?php echo $block->getData('display_rating') ?>"
                       data-display_addtocart="<?php echo $block->getData('display_addtocart') ?>"
                       data-display_addtowishlist="<?php echo $block->getData('display_addtowishlist') ?>"
                       data-display_addtocompare="<?php echo $block->getData('display_addtocompare') ?>"
                       data-display_swatch_attributes="<?php echo $block->getData('display_swatch_attributes') ?>"
                       data-display_productname="<?php echo $block->getData('display_productname') ?>"
                       data-display_name_single_line="<?php echo $block->getData('display_name_single_line') ?>"
                       data-display_price="<?php echo $block->getData('display_price') ?>"
                       data-countdown="<?php echo $block->getData('countdown') ?>">
                        <?php echo $tab['label'] ?>
                    </a>
                </li>
            <?php endforeach ?>
        </ul>
    </div>
    <div class="widget-tab-content tab-content">
        <?php foreach ($tabs as $index => $tab): ?>
        <div id="<?php echo $id . '-' . $tab['id'] ?>" class="tab-pane<?php echo $index==0 ? ' active' : '' ?>">
            <?php if ($index > 0): ?>
        </div>
    <?php continue ?>
    <?php endif ?>
        <?php echo $block->renderCollection($tab['type'], $tab['value'], $template) ?>
    </div>
    <?php endforeach ?>
</div>
<script>
    var BASE_URL = '<?php /* @escapeNotVerified */ echo $block->getUrl('*') ?>';
    var FORM_KEY = '<?php /* @escapeNotVerified */ echo $block->getFormKey() ?>';
</script>
<script>
    require([
        "jquery",
        "js/jquery.noconflict",
        "cleverProductMage"
    ], function ($,noConflict,cleverProductMage) {
        $(function() {
            $('#<?php echo $id ?>').cleverProductMage({
                animation: <?php echo $block->getData('animation')? $block->getData('animation'):$block->getConfig('animation') ?>,
                collectionUrl: '<?php echo $block->getUrl('cleverproduct/collection/collection') ?>',
                spinnerClass: 'spinner',
                spinnerImg: '<img class="img-loader" src="<?php echo $block->getViewFileUrl('CleverSoft_Base::images/bx_loader.gif'); ?>">',
                parallax: <?php echo $block->getConfig('parallax') ?$block->getConfig('parallax'):$block->getData('parallax') ?>,
                carousel: <?php echo $block->getConfig('carousel')? $block->getConfig('carousel'):$block->getData('carousel') ?>,
                carouselConfig: null,
                countdown: <?php echo $block->getConfig('countdown')? $block->getConfig('countdown') : $block->getData('countdown')?>,
                countdownConfig: null,
                kenburns: <?php echo $block->getConfig('kenburns')?$block->getConfig('kenburns'):$block->getData('kenburns') ?>
            });
        });
    });
</script>
<?php //Mage::log(microtime() - $t) ?>
</div>
