<!--
** Header Logo Center
** Create date 15/02/2017
-->
<?php
$full_header_width = $block->getData('full_header_width');
$compareHeader = $block->getData('compare');
$wishlistHeader = $block->getData('wishlist');
$sticky_logo = $block->getConfig('cleversoftbase/header/sticky_logo');
$logoSrc = $this->getUrl('pub/media/wysiwyg/mato/logo/', ['_secure' => $this->getRequest()->isSecure(),'_type'=>\Magento\Framework\UrlInterface::URL_TYPE_WEB]).$sticky_logo;
?>
<div class="panel wrapper">
    <div class="header-panel <?php echo ($full_header_width == 1 ? '' : 'container')?>">
        <!--div class="topbar-container">
            <?php //echo $this->getChildHtml("top.contact"); ?>
            <?php //echo $this->getChildHtml("currency"); ?>
            <?php //echo $this->getChildHtml("store_language"); ?>
        </div-->
    </div>
</div>
<div class="header-content <?php echo ($full_header_width == 1 ? '' : 'container')?>">
    <div class="zoo-header-content-block right">
		<div id="header-layout-search">
			<a href="javascript:void(0)"><span class="cs-font clever-icon-search-4"></span></a>
		</div>
        <?php //echo $this->getChildHtml("top.search"); ?>
        <?php echo $this->getChildHtml("header.links"); ?>
        <?php echo $this->getChildHtml("minicart"); ?>
    </div>
</div>
<div class="top-menu" id="zoo-sticky-header">
    <div class="<?php echo ($full_header_width == 1 ? '' : 'container')?>">
        <div class="zoo-menu-content">
            <?php echo $this->getChildHtml("main.menu"); ?>
            <?php echo $this->getChildHtml("logo"); ?>
			
        </div>
    </div>
</div>