<?php
/**
 * @category    CleverSoft
 * @package     CleverBase
 * @copyright   Copyright © 2017 CleverSoft., JSC. All Rights Reserved.
 * @author 		ZooExtension.com
 * @email       magento.cleversoft@gmail.com
 */
 
$full_header_width = $block->getData('full_header_width');
$compareHeader = $block->getData('compare');
$wishlistHeader = $block->getData('wishlist');
$sticky_logo = $block->getConfig('cleversoftbase/header/sticky_logo');
$logoSrc = $this->getUrl('pub/media/wysiwyg/mato/logo/', ['_secure' => $this->getRequest()->isSecure(),'_type'=>\Magento\Framework\UrlInterface::URL_TYPE_WEB]).$sticky_logo;
?>

<div class="panel wrapper">

</div>
<div class="header-content <?php echo ($full_header_width == 1 ? '' : 'container')?>" id="header-sticky-mobile">
    <div class="row">
        <div class="col-xs-12 col-sm-3">
            <span data-action="toggle-nav" class="action zoo-menu-label">
                <span class="cs-font clever-icon-menu-5"></span>
            </span>
            <?php echo $this->getChildHtml("logo"); ?>
        </div>
        <div class="col-xs-12 col-sm-9">
            <div class="header-panel">
                <div class="topbar-container">
                    <div class="col-md-4 hidden-sm hidden-xs">
                        <?php echo $this->getChildHtml("top.contact"); ?>
                    </div>
                    <div class="col-md-8 col-sm-12 col-sx-12 topbar-right">
                        <?php echo $this->getChildHtml("top.search"); ?>
                        <?php echo $this->getChildHtml("currency"); ?>
                        <?php echo $this->getChildHtml("store_language"); ?>
                    </div>
                </div>
            </div>

            <div class="top-menu" id="zoo-sticky-header">
                    <div class="d-flex justify-content-between align-items-center zoo-menu-content">
                        <div class="logo-sticky">
                            <?php if ($block->isHomePage()):?>
                            <strong>
                                <?php else: ?>
                                <a href="<?php echo $block->getUrl(''); ?>">
                                    <?php endif ?>
                                    <img src="<?php echo $logoSrc; ?>" width="auto" height="auto"/>
                                    <?php if ($block->isHomePage()):?>
                            </strong>
                        <?php else:?>
                            </a>
                        <?php endif?>
                        </div>
                        <?php echo $this->getChildHtml("main.menu"); ?>
                        <div class="zoo-header-user">
                            <?php echo $this->getChildHtml("minicart"); ?>
                            <?php if ($wishlistHeader) echo $this->getChildHtml("wishlist"); ?>
                            <?php if ($compareHeader) echo $this->getChildHtml("compare_link"); ?>
                            <?php echo $this->getChildHtml("header.links"); ?>
                        </div>
                    </div>
            </div>
        </div>
    </div>
</div>